# Generated by Django 5.2.4 on 2025-08-05 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Feature title (minimum 5 characters)",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed feature description"),
                ),
                ("votes", models.IntegerField(default=0, help_text="Number of votes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-votes", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-votes", "-created_at"],
                        name="core_featur_votes_1c5315_idx",
                    )
                ],
            },
        ),
    ]
